version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app --log-level=debug -k gevent
    depends_on:
      - redis
    env_file:
      variable.env
  redis:
    image: redis
  celery:
    build: .
    command: celery worker -l info -A geoservice.tasks.celery
    depends_on:
      - redis
    environment:
      env_file:
        variable.env
